transit in T domain

diff --git a/hue/hue b/hue/hue
--- a/hue/hue
+++ b/hue/hue
@@ -137,7 +137,7 @@ interpolate () { # this function takes
           TOB=$8
 	  STEP=$9
           ;;
-      ct)
+      ct|[Tt])
           FROM1=$3
           FROMB=$4
           TO1=$5
@@ -184,6 +184,11 @@ interpolate () { # this function takes
 	  debug mirek:$VAL1
           echo $SCHEMA $VAL1 $BRI
           ;;
+      [tT])
+	  VAL1=$( calc %d "((($TO1 / $FROM1) ** (1.0/$STEPS)) ** $STEP ) * $FROM1" )
+	  debug temp:$VAL1
+	  echo t $VAL1  $BRI
+	  ;;
       pair)
 	  VAL1=$( calc "($TO1 - $FROM1)/$STEPS * $STEP + $FROM1" )
 	  VAL2=$( calc "($TO2 - $FROM2)/$STEPS * $STEP + $FROM2" )          
@@ -333,26 +338,27 @@ hue transit {to_color} {to_brightness} - must be in currently used schema
         case $schema in
             xy|hue)                                
                 if [ "$4" = "" ] ; then
-                    show_help 1 too few parameters $*
+                    show_help 1 too few parameters: two numbers expected $*
                 fi
                 set_bulb_color $light $schema $2 $3 $4
                 shift 4
                 ;;
             ct)
                 if [ "$3" = "" ] ; then
-                    show_help 1 too few parameters $*
+                    show_help 1 too few parameters: mirek expected $*
                 fi
                 set_bulb_color $light $schema $2 $3
                 shift 3
                 ;;
-            T*)
-                COLOR=$( describe_color $schema )
+            [tT])
                 if [ "$2" = "" ] ; then
-                    show_help 1 too few parameters $*
+                    show_help 1 too few parameters: tempearature expected $*
                 fi
-                schema=xy
-                set_bulb_color $light xy $COLOR $2
-                shift 2
+                schema=T
+		COLOR=T$2
+		SAVED_TEMP=$2
+                set_bulb_color $light $COLOR $3 
+                shift 3
                 ;;
             *)
                 COLOR=$( describe_color $schema )
@@ -367,11 +373,29 @@ hue transit {to_color} {to_brightness} - must be in currently used schema
     fi
     
     schema=$1
+
     if [ "$schema" = "" ] ; then
 	show_help 1 no target color description
     fi
     SAVED_COLOR=$( get_color $light )
     SAVED_SCHEMA=$( first $SAVED_COLOR )
+    SAVED_BRIGHTNESS=$( get_brightness $light )
+    case "$SAVED_SCHEMA-$schema" in
+	xy-xy|ct-ct|hue-hue|[tT]-[tT])
+	    feedback transit 
+	    :
+	    ;;
+	[tT]-xy|xy-[tT])
+	    feedback it is ok
+	    :
+	    ;;
+	ct-xy)
+	    SAVED_COLOR="$( ct_2_xy $( first $SAVED_COLOR ) )"
+	    ;;
+	*)
+	    :	    show_help 1 Cannot transit from $SAVED_SCHEMA to $schema
+	    ;;
+    esac
     feedback transit from $SAVED_COLOR to "$@" in $STEPS steps
     for i in $( seq 1 $STEPS ) ; do
         case $1 in # hands off 
@@ -385,13 +409,12 @@ hue transit {to_color} {to_brightness} - must be in currently used schema
                     show_help 1 too few parameters specified $*
                 fi
                 NEW_COLOR=$( interpolate $STEPS $SAVED_COLOR $2 $3  $i) ;;
-            T*)      
-                if [ "$2" = "" ] ; then
+            [tT])      
+                if [ "$3" = "" ] ; then
                     show_help 1 too few parameters specified $*
                 fi
-                COLOR=$( describe_color $1 )
-                schema=xy
-                NEW_COLOR=$( interpolate $STEPS $SAVED_COLOR $COLOR $2 $i) ;;
+                schema=t
+                NEW_COLOR=$( interpolate $STEPS T $SAVED_TEMP $SAVED_BRIGHTNESS $2 $3 $i) ;;
             *)      
                 if [ "$2" = "" ] ; then
                     show_help 1 too few parameters specified $*
@@ -400,11 +423,11 @@ hue transit {to_color} {to_brightness} - must be in currently used schema
                 schema=xy
                 NEW_COLOR=$( interpolate $STEPS $SAVED_COLOR $COLOR $2 $i) ;;           
         esac
-        if [ "$schema" != "$SAVED_SCHEMA" ] ; then
-            # TODO: transfer  ct -> xy
-            echo "Cannot transit from $SAVED_SCHEMA to $schema"
-            exit 1
-        fi
+#         if [ "$schema" != "$SAVED_SCHEMA" ] ; then
+#             # TODO: transfer  ct -> xy
+#             echo "Cannot transit from $SAVED_SCHEMA to $schema"
+#             exit 1
+#         fi
         set_bulb_color $light $NEW_COLOR 
         sleep $SLEEP
         maybe_give_up $light
@@ -792,8 +815,12 @@ hue set brightness {brightness:1-254} - setting brightnes
     maybe_help_needed "$@"
     if [ "$1" = "" ] ; then
         show_help 1 no brightness value specified
-    fi    
-    BRIGHTNESS=$1
+    fi
+    case $1 in
+	max) BRIGHTNESS=254 ;;
+	min) BRIGHTNESS=1 ;;
+	*)  BRIGHTNESS=$1 ;;
+    esac
     mandatory_lights
     feedback setting brightness of light $light to $BRIGHTNESS    
     FAKE_bri=$BRIGHTNESS
@@ -809,9 +836,15 @@ hue [set] color hue {hue:0-65535} {saturation:1-254} {brightness:1-254}
     mandatory_lights
     if [ "$3" = "" ] ; then
         show_help 1 $*
+    else
+	case $3 in
+	    max) BRIGHTNESS=254 ;;
+	    min) BRIGHTNESS=1 ;;
+	    *)  BRIGHTNESS=$3 ;;
+	esac
     fi    
     feedback setting hue to "$@"
-    polite_curl -s -X PUT -d '{"on":true, "hue":'$1', "sat":'$2',"bri":'$3'}' http://$bridge_ip/api/$user_key/lights/$light/state     
+    polite_curl -s -X PUT -d '{"on":true, "hue":'$1', "sat":'$2',"bri":'$BRIGHTNESS'}' http://$bridge_ip/api/$user_key/lights/$light/state     
 }
 
 set_xy () {
@@ -823,11 +856,17 @@ CIE set color xy {x} {y} {brightness:1-254}
     maybe_help_needed "$@"
     if [ "$3" = "" ] ; then
         show_help 1 too few parameters specified
+    else
+	case $3 in
+	    max) BRIGHTNESS=254 ;;
+	    min) BRIGHTNESS=1 ;;
+	    *)  BRIGHTNESS=$3 ;;
+	esac
     fi    
     mandatory_lights
     
-    feedback setting CIE color of light $light to "$@"
-    polite_curl -s -X PUT -d '{"on":true, "xy":['$1', '$2'], "bri":'$3'}' http://$bridge_ip/api/$user_key/lights/$light/state 
+    feedback setting CIE color of light $light to "$@" 
+    polite_curl -s -X PUT -d '{"on":true, "xy":['$1', '$2'], "bri":'$BRIGHTNESS'}' http://$bridge_ip/api/$user_key/lights/$light/state 
 }
 
 set_ct () {
@@ -838,10 +877,16 @@ hue set color ct  {mirek:153-500} {brightness:1-254}
     maybe_help_needed "$@"    
     if [ "$2" = "" ] ; then
         show_help 1 too few parameters specified
+    else
+	case $2 in
+	    max) BRIGHTNESS=254 ;;
+	    min) BRIGHTNESS=1 ;;
+	    *)  BRIGHTNESS=$2 ;;
+	esac
     fi    
     mandatory_lights
     feedback setting light $light to  mirek "$@"
-    polite_curl -s -X PUT -d '{"on":true, "ct":'$1', "bri":'$2'}' http://$bridge_ip/api/$user_key/lights/$light/state 
+    polite_curl -s -X PUT -d '{"on":true, "ct":'$1', "bri":'$BRIGHTNESS'}' http://$bridge_ip/api/$user_key/lights/$light/state 
 }
     
 set_color () { 
@@ -853,7 +898,7 @@ hue set color
             or named color:       
           red|orange|yellow|green|blue|violet
             or temperature 
-          T1500 - T7000 -- color temperature in multiples of 500
+          T1000 - T20000 -- color temperature in K
 "
     maybe_help_needed "$@"
     mandatory_lights
@@ -916,6 +961,14 @@ set_bulb_color () { # this is Internal procedure not accessible
             set_hue "$@"
             FAKE_hue="hue $*"
             ;;
+	[tT])
+            if [ "$2" = "" ] ; then
+                show_help 1 temperature and brightness expected
+            fi
+	    COLOR=$( K_2_xy T$1 )
+	    FAKE_t="T $1"
+	    set_xy $COLOR $2 T$1
+	    ;;
         *)
             COLOR=$( describe_color $schema )
             FAKE_xy="xy $COLOR $1"
